#lang racket

(define (take n lst)
  (cond ((zero? n) '())
        ((>= n (length lst)) lst)
        (else (cons (car lst) (take (- n 1) (cdr lst))))
        )
  )

(define (drop n lst)
  (cond ((zero? n) lst)
        ((>= n (length lst)) '())
        (else (drop (- n 1) (cdr lst)))
        )
  )

(define (all? p? lst)
        (or (null? lst)
            (and (p? (car lst)) (all? p? (cdr lst)))
            )
  )

(define (any? p? lst)
        (and (not (null? lst))
             (or (p? (car lst) (all? p? (cdr lst))))
        )
  )

(define (zip l1 l2)
  (if (or (null? l1) (null? l2))
      '()
      (cons (cons (car l1) (car l2)) (zip (cdr l1) (cdr l2)))
      )
  )

(define (zipWith op l1 l2)
  (if (or (null? l1) (null? l2))
      '()
      (cons (op (car l1) (car l2)) (zipWith op (cdr l1) (cdr l2)))
      )
  )
